name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide details to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Connect to NATS server at...
        2. Run query: SELECT * FROM nats_scan(...)
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages if applicable.
    validations:
      required: true

  - type: input
    id: duckdb-version
    attributes:
      label: DuckDB Version
      placeholder: "v1.4.1"
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      placeholder: "v0.1.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Linux
        - macOS
        - Windows
        - WebAssembly
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information (NATS server version, configuration, etc.)

